#!/usr/bin/python
import argparse, os, logging
import dminer

logger = logging.getLogger("dminer")

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler = logging.StreamHandler()
handler.setFormatter(formatter)
logger.addHandler(handler)

def main():
	"""
	"""
	parser = argparse.ArgumentParser()
	subparsers = parser.add_subparsers()
	
	sink_subparser = subparsers.add_parser("scrape", help=dminer.sinks.__doc__)
	dminer.sinks.prepare_cli(sink_subparser)
	
	ingestion_subparser = subparsers.add_parser("ingest", help=dminer.ingestion.__doc__)
	dminer.ingestion.prepare_cli(ingestion_subparser)
	
	store_subparser = subparsers.add_parser("store", help=dminer.stores.__doc__)
	dminer.stores.prepare_cli(store_subparser)
	
	args = parser.parse_args()
	args.func(args)

if __name__ == '__main__':
	main()
